name: Run Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: cooking-clips-test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Environment Variables
      run: |
        echo "export SECRET_KEY='${{ secrets.AUTH_TOKEN_SECRET_KEY }}'" >> $GITHUB_ENV
        echo "export DB_USERNAME=postgres" >> $GITHUB_ENV
        echo "export DB_PASSWORD=admin" >> $GITHUB_ENV
        echo "export TEST_DB_NAME=cooking-clips-test" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source $GITHUB_ENV
        pytest